from subsystems.propulsion.motors.components.base_component import Component
from subsystems.propulsion.motors.helpers.flow_state import FlowState
from subsystems.propulsion.motors.helpers.gas_model import GasModel
from subsystems.propulsion.motors.components.reactors.black_box_reactor_specs import BlackBoxReactorSpecs


class BlackBoxReactor(Component):
    """
    Reactor modelled as a black box with:
        - Pressure drop of air
        - Temperature increase of air.
    Computes required thermal energy generated by the reactor.
    """
    def __init__(self, specs: BlackBoxReactorSpecs, gas_model: GasModel, name: str = "Black box reactor"):
        super().__init__(gas_model, name)
        self.PR_loss = specs.PR_loss
        self.T_tet = specs.T_tet

    def process(self, flow: FlowState) -> FlowState:
        self.last_inlet = flow
        Tt_in = flow.Tt
        Pt_in = flow.Pt
        cp_in = self.gas.cp(Tt_in)
        # Simplified constant cp model for products; you can refine
        cp_out = self.gas.cp(self.T_tet)
        # use cea for h_out and h_in

        # Thermal power into air
        Q_air = flow.m_dot * cp * (self.T_tet - Tt_in)
        Q_reactor = Q_air / eta_thermal

        Pt_out = self.PR_loss * Pt_in

        out = FlowState(
            Tt=self.T_tet,
            Pt=Pt_out,
            m_dot=flow.m_dot)

        self.last_exit = out
        return out